; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.36"

; Modules
projects[backup_migrate][version] = "3.0"

projects[ctools][version] = "1.7"

projects[jquery_update][version] = "2.5"

projects[oauth][version] = "3.2"

projects[twitter][version] = "5.8"

projects[views][version] = "3.11"

; Themes
projects[bootstrap][version] = "3.0"

